In [169]:
#Part 1: Dataset Creation
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)



Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [170]:
# Part 2: Basic Array Understanding
# Question 1: Array Dimensions
# The finance manager wants to confirm how many stores and product categories are present in the data.

# Write NumPy code to display:

# Number of dimensions in sales_data
print(np.array(sales_data).ndim)

# Shape of sales_data
print(np.array(sales_data).shape)

# Total number of values
print(np.array(sales_data).size)

# Data type of the array
print(np.array(sales_data).dtype)

# Memory occupied by the array
print(np.array(sales_data).nbytes)



2
(5, 6)
30
int64
240


In [171]:
# Question 2: Store and Category Count
# Calculate the following:

# Total number of stores
print(np.array(stores).size)

# Total number of product categories
print(np.array(categories).size)

# Total number of store-category combinations
print(np.array(sales_data).size)



5
6
30


In [172]:
# Question 3: Sales Data Type Conversion
# The reporting application requires sales values in floating-point format.

# Convert sales_data into:

# float32
f32 = np.array(sales_data,dtype = np.float32)

# float64
f64 = np.array(sales_data,dtype = np.float64)

print(f32)
print(f64)
# Compare the memory used by both arrays.
print(f32.nbytes)
print(f64.nbytes)



[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
120
240


In [173]:
# Part 3: Indexing and Data Extraction
# Question 4: Bengaluru Store Analysis
# The Bengaluru regional manager wants to review sales for all product categories.

# Extract and display the complete sales row for Bengaluru.

sales_banglore = sales_data[0]
print(sales_banglore)


[850000 420000 310000 275000 190000 225000]


In [174]:
# Question 5: Mumbai Cost Analysis
# Extract the total cost incurred by the Mumbai store for all product categories.

Mumbai_product_totalcost =cost_data[-2].sum()
print(Mumbai_product_totalcost)

2065000


In [175]:
# Question 6: Electronics Sales Across Stores
# The electronics department wants to compare its sales performance across all five stores.

# Extract the Electronics sales column from sales_data.

Electronics_sales = sales_data[:,0]
print(Electronics_sales)


[ 850000  780000  920000 1050000  690000]


In [176]:
# Question 7: Clothing Cost Across Stores
# Extract the Clothing cost for every store from cost_data.

Clothing_cost = cost_data[:,2]
print(Clothing_cost)

[220000 210000 245000 265000 205000]


In [177]:
# Question 8: Hyderabad Furniture Performance
# Find the following for Hyderabad:

# Furniture sales
# Furniture cost
# Furniture profit

# Furniture sales
furniture_sales = sales_data[1,3]
print(furniture_sales)

# Furniture cost
furniture_cost = cost_data[1,3]
print(furniture_cost)

# Furniture profit
furniture_profit = furniture_sales - furniture_cost
print(furniture_profit)

310000
225000
85000


In [178]:
# Question 9: Chennai Category Range
# Extract Chennai’s sales for the following categories:

# Groceries
# Clothing
# Furniture
# Use array slicing.

chennai_sales = sales_data[2,1:4]
print(chennai_sales)
print("Groceries- ",chennai_sales[0])
print("Clothing- ",chennai_sales[1])
print("Furniture- ",chennai_sales[2])

# # Groceries
# Groceries_sales = sales_data[2,1]
# print(Groceries_sales)

# # Clothing
# clothing_sales = sales_data[2,2]
# print(clothing_sales)

# # Furniture
# Furniture_sales = sales_data[2,3]
# print(Furniture_sales)

[390000 340000 260000]
Groceries-  390000
Clothing-  340000
Furniture-  260000


In [179]:
# Question 10: Selected Store Analysis
# Extract sales data for:

# Bengaluru
# Chennai
# Pune
# Include only:

# Electronics
# Clothing
# Beauty
# Use advanced indexing.

selected_store = sales_data[[0,2,-1]][:,[0,2,4]]
selected_store

array([[850000, 310000, 190000],
       [920000, 340000, 185000],
       [690000, 280000, 175000]])

In [180]:
# Part 4: Sales Aggregation
# Question 11: Company-Wide Sales
# Calculate the total sales revenue generated by all stores and all categories.

total_sales = sales_data.sum()
print(total_sales)


11675000


In [181]:
# Question 12: Store-Wise Sales
# Calculate total sales revenue for each store.

# Display the result together with the store names.

# Expected output format:

# Bengaluru: total sales
# Hyderabad: total sales
# Chennai: total sales
# Mumbai: total sales
# Pune: total sales

storewise_total_sales = sales_data.sum(axis=1)
print(storewise_total_sales)
print('\n')
for i in range(len(stores)):
  print(stores[i], ":", storewise_total_sales[i])


[2270000 2295000 2310000 2820000 1980000]


Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


In [182]:
# Question 13: Category-Wise Sales
# Calculate total sales for each product category across all stores.

# Display each category name with its total sales.

CategoryWise_total_Sales = sales_data.sum(axis=0)
print(CategoryWise_total_Sales)
print('\n')

for i in range(len(categories)):
  print(categories[i], ":", CategoryWise_total_Sales[i])


[4290000 2185000 1600000 1415000 1010000 1175000]


Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


In [183]:
# Question 14: Average Sales Per Store
# Calculate the average sales generated by each store across all six product categories.

Average_Sales_Per_Store = sales_data.mean(axis=1)
print(Average_Sales_Per_Store)

print("\n")

for i in range(len(stores)):
  print(stores[i], ":", Average_Sales_Per_Store[i])


[378333.33333333 382500.         385000.         470000.
 330000.        ]


Bengaluru : 378333.3333333333
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


In [184]:
# Question 15: Average Sales Per Category
# Calculate the average sales of each product category across the five stores.

CategoryWise_total_Sales = sales_data.mean(axis=0)
print(CategoryWise_total_Sales)
print('\n')

for i in range(len(categories)):
  print(categories[i], ":", CategoryWise_total_Sales[i])

[858000. 437000. 320000. 283000. 202000. 235000.]


Electronics : 858000.0
Groceries : 437000.0
Clothing : 320000.0
Furniture : 283000.0
Beauty : 202000.0
Sports : 235000.0


In [185]:
# Question 16: Highest-Selling Store
# Identify:

# Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store
# Use np.argmax().

storewise_sales = sales_data.sum(axis=1)
print(storewise_sales)

Highest_selling_store_index = np.argmax(storewise_sales)
# print(Highest_selling_store_index)

print("Index of highest sales: ",Highest_selling_store_index)
print("Name of store: ",stores[Highest_selling_store_index])
print("Total sales: ",storewise_sales[Highest_selling_store_index])

[2270000 2295000 2310000 2820000 1980000]
Index of highest sales:  3
Name of store:  Mumbai
Total sales:  2820000


In [186]:
# Question 17: Lowest-Selling Store
# Identify the store with the lowest overall sales.

# Use np.argmin().

storewise_sales = sales_data.sum(axis=1)
print(storewise_sales)

Lowest_selling_store_index = np.argmin(storewise_sales)
print(stores[Lowest_selling_store_index],":",Lowest_selling_store_index)


[2270000 2295000 2310000 2820000 1980000]
Pune : 4


In [187]:
# Question 18: Highest-Selling Category
# Find the product category that generated the highest total sales across the company.

category_sales = sales_data.sum(axis=0)
print(category_sales)

Highest_category_sales_index = np.argmax(category_sales)
print("Index is",Highest_category_sales_index,
      ", product is ",categories[Highest_category_sales_index],
      "and Total sales is",
      category_sales[Highest_category_sales_index])


[4290000 2185000 1600000 1415000 1010000 1175000]
Index is 0 , product is  Electronics and Total sales is 4290000


In [188]:
# Question 19: Lowest-Selling Category
# Find the product category with the lowest total sales across all stores.

category_sales = sales_data.sum(axis=0)
print(category_sales)

Lowest_category_sales_index = np.argmin(category_sales)
print("Index is",Lowest_category_sales_index,
      ", product is ",categories[Lowest_category_sales_index],
      "and Total sales is",
      category_sales[Lowest_category_sales_index])


[4290000 2185000 1600000 1415000 1010000 1175000]
Index is 4 , product is  Beauty and Total sales is 1010000


In [189]:
# Part 5: Cost Analysis
# Question 20: Total Company Cost
# Calculate the total cost incurred by SmartMart across all stores and product categories.

Total_Company_Cost = cost_data.sum()
print(Total_Company_Cost)


8600000


In [190]:
# Question 21: Store-Wise Cost
# Calculate the total cost incurred by each store.

Store_Wise_Cost = cost_data.sum(axis=1)
print(Store_Wise_Cost)

[1665000 1685000 1710000 2065000 1475000]


In [191]:
# Question 22: Category-Wise Cost
# Calculate the total cost incurred for each product category across all stores.

Category_Wise_Cost = cost_data.sum(axis=0)
print(Category_Wise_Cost)


[3250000 1660000 1145000 1045000  665000  835000]


In [192]:
# Question 23: Most Expensive Store
# Identify the store with the highest total operating cost.

Store_Wise_Cost = cost_data.sum(axis=1)
highest_total_operating_cost = np.argmax(Store_Wise_Cost)
print(stores[highest_total_operating_cost])

Mumbai


In [193]:
# Question 24: Lowest-Cost Store
# Identify the store with the lowest total cost.

Store_Wise_Cost = cost_data.sum(axis=1)
lowest_total_operating_cost = np.argmin(Store_Wise_Cost)
print(stores[lowest_total_operating_cost])


Pune


In [194]:
# Question 25: Most Expensive Product Category
# Determine which product category has the highest total cost across all stores.

cat_wise_cost = cost_data.sum(axis=0)
Expensive_Product_Category = np.argmax(cat_wise_cost)
print(categories[Expensive_Product_Category])


Electronics


In [195]:
# Part 6: Profit Analysis Using Two Arrays
# Question 26: Profit Matrix
# Calculate the profit generated for every store and product category.

# Use:

# profit_data = sales_data - cost_data
# Display the complete profit matrix.
profit_data = sales_data - cost_data
print(profit_data)


[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [196]:
# Question 27: Store-Wise Profit
# Calculate the total profit generated by each store.

store_wise_profit = sales_data.sum(axis=1) - cost_data.sum(axis=1)
print(store_wise_profit)


[605000 610000 600000 755000 505000]


In [197]:
# Question 28: Category-Wise Profit
# Calculate the total profit generated by each product category.

Category_Wise_Profit = sales_data.sum(axis=0) - cost_data.sum(axis=0)
print(Category_Wise_Profit)


[1040000  525000  455000  370000  345000  340000]


In [198]:
# Question 29: Most Profitable Store
# Identify the store that generated the highest total profit.

# Display:

# Store name
# Total sales
# Total cost
# Total profit

store_wise_profits = sales_data.sum(axis=1) - cost_data.sum(axis=1)
most_profitable_store = np.argmax(store_wise_profits)

print("Store name: ",stores[most_profitable_store])
print("Total sales: ",sales_data.sum(axis=1)[most_profitable_store])
print("Total cost: ",cost_data.sum(axis=1)[most_profitable_store])
print("Total profit: ",store_wise_profits[most_profitable_store])



Store name:  Mumbai
Total sales:  2820000
Total cost:  2065000
Total profit:  755000


In [199]:
# Question 30: Least Profitable Store
# Identify the store that generated the lowest total profit.

store_wise_profits = sales_data.sum(axis=1) - cost_data.sum(axis=1)
least_profitable_store = np.argmin(store_wise_profits)
print(stores[least_profitable_store])


Pune


In [200]:
# Question 31: Most Profitable Category
# Find the category with the highest total profit across all stores.

cat_wise_profits = sales_data.sum(axis=0) - cost_data.sum(axis=0)
most_profitable_cat = np.argmax(cat_wise_profits)
print(categories[most_profitable_cat])


Electronics


In [201]:
# Question 32: Least Profitable Category
# Find the category with the lowest total profit.

cat_wise_profits = sales_data.sum(axis=0) - cost_data.sum(axis=0)
least_profitable_cat = np.argmin(cat_wise_profits)
print(categories[least_profitable_cat])


Sports


In [202]:
# Question 33: Maximum Individual Profit
# Find the highest profit generated by any single store-category combination.

# Display:

# Profit amount
# Store name
# Product category
# Use np.unravel_index().

profit_data = sales_data - cost_data
max_index = np.unravel_index(np.argmax(profit_data),profit_data.shape)
### Not asked for my reference
print(profit_data)
###########################
print("\n")
print("Profit Amount:", profit_data[max_index])
print("Store Name:", stores[max_index[0]])
print("Product Category:", categories[max_index[1]])


[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Profit Amount: 260000
Store Name: Mumbai
Product Category: Electronics


In [203]:
# Question 34: Minimum Individual Profit
# Find the smallest profit generated by a store-category combination.

# Display the corresponding store and category.

profit_date = sales_data - cost_data
minimum_profit = np.unravel_index(np.argmin(profit_data),profit_data.shape)

print("Least profit amount:",profit_data[minimum_profit])
print("Least profit store:",stores[minimum_profit[0]])
print("Least profit category:",categories[minimum_profit[1]])


Least profit amount: 55000
Least profit store: Pune
Least profit category: Furniture


In [204]:
# Part 7: Profit Margin Analysis
# Question 35: Profit Margin Matrix
# Calculate the profit margin percentage for every store-category combination.

# Use:

# profit_margin = (profit_data / sales_data) * 100
# Round the result to two decimal places.

profit_data = sales_data - cost_data

profit_margin = np.round((profit_data / sales_data)* 100,2)
print(profit_margin)


[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [205]:
# Question 36: Store-Wise Profit Margin
# Calculate the overall profit margin percentage for each store using:

# Store Profit Margin =
# Total Store Profit / Total Store Sales × 100

total_store_profit = sales_data.sum(axis=1)- cost_data.sum(axis=1)
total_store_sales = sales_data.sum(axis=1)

store_profit_margin = np.round((total_store_profit / total_store_sales) * 100,2)
print(store_profit_margin)


[26.65 26.58 25.97 26.77 25.51]


In [206]:
# Question 37: Category-Wise Profit Margin
# Calculate the overall profit margin percentage for each product category.
total_cat_profit = sales_data.sum(axis=0)- cost_data.sum(axis=0)
total_cat_sales = sales_data.sum(axis=0)

cat_profit_margin = np.round((total_cat_profit / total_cat_sales) * 100,2)
print(cat_profit_margin)


[24.24 24.03 28.44 26.15 34.16 28.94]


In [207]:
# Question 38: Best Store by Profit Margin
# Identify the store with the highest overall profit margin.

profits_store = sales_data.sum(axis=1) - cost_data.sum(axis=1)
total_store_sales = sales_data.sum(axis=1)
profit_store_margin = (profits_store / total_store_sales) * 100

Highest_profit_store_margin = np.argmax(profit_store_margin)

print(stores[Highest_profit_store_margin])


Mumbai


In [208]:
# Question 39: Best Category by Profit Margin
# Identify the product category with the highest profit margin.

cat_profits = sales_data.sum(axis=0) - cost_data.sum(axis=0)
total_cat_sales = sales_data.sum(axis=0)
cat_profit_margin =  cat_profits/total_cat_sales * 100
highest_cat_profit_margin = np.argmax(cat_profit_margin)

print(categories[highest_cat_profit_margin])


Beauty


In [209]:
# Question 40: Low-Margin Transactions
# Management considers a profit margin below 22% to be weak.

# Find all store-category combinations where the profit margin is below 22%.

# Display:

# Store
# Category
# Sales
# Cost
# Profit
# Profit margin
# Use Boolean indexing.

store_cat_profits = sales_data - cost_data

store_cat_profits_margin = np.round(store_cat_profits / sales_data * 100,2)
#print(store_cat_profits_margin)

low_margin = store_cat_profits_margin < 22
#print(low_margin)

rows,cols = np.where(low_margin)

if len(rows)==0:
  print("All the values are above 22")
else:
  for rows,cols in zip(rows,cols):
    print("Store:", stores[rows])
    print("Category:", categories[cols])
    print("Sales:", sales_data[rows, cols])
    print("Cost:", cost_data[rows, cols])
    print("Profit:", store_cat_profits[rows, cols])
    print("Profit Margin:", store_cat_profits_margin[rows, cols], "%")


All the values are above 22


In [210]:
# Part 8: Boolean Filtering
# Question 41: High Sales Values
# Find all sales values greater than ₹5,00,000.

high_sales_values = sales_data > 500000

row,col = np.where(high_sales_values)

for row,col in zip(row,col):
  print(stores[row],categories[col],sales_data[row,col])

Bengaluru Electronics 850000
Hyderabad Electronics 780000
Chennai Electronics 920000
Mumbai Electronics 1050000
Mumbai Groceries 510000
Pune Electronics 690000


In [211]:
# Question 42: Low Sales Values
# Find all sales values below ₹2,00,000.

low_sales_value = sales_data < 200000

row,col = np.where(low_sales_value)

for row,col in zip(row,col):
  print(stores[row],categories[col],sales_data[row,col])

Bengaluru Beauty 190000
Chennai Beauty 185000
Pune Beauty 175000


In [212]:
# Question 43: High Profit Values
# Find all store-category combinations where profit is greater than ₹1,50,000.

profit_value = sales_data - cost_data

high_profit_value = profit_value > 150000

row,col = np.where(high_profit_value)

for row,col in zip(row,col):
  print(stores[row],categories[col],profit_value[row,col])


Bengaluru Electronics 210000
Hyderabad Electronics 190000
Chennai Electronics 220000
Mumbai Electronics 260000
Pune Electronics 160000


In [213]:
# Question 44: Moderate Sales Range
# Find sales values between ₹2,50,000 and ₹5,00,000.

# Use np.logical_and().

mod_range_sales = np.logical_and(sales_data > 250000,sales_data < 500000)

row,col = np.where(mod_range_sales)

for row,col in zip(row,col):
  print(stores[row],categories[col],sales_data[row,col])


Bengaluru Groceries 420000
Bengaluru Clothing 310000
Bengaluru Furniture 275000
Hyderabad Groceries 460000
Hyderabad Clothing 295000
Hyderabad Furniture 310000
Chennai Groceries 390000
Chennai Clothing 340000
Chennai Furniture 260000
Mumbai Clothing 375000
Mumbai Furniture 345000
Mumbai Sports 290000
Pune Groceries 405000
Pune Clothing 280000


In [214]:
# Question 45: Premium Performance
# A store-category combination is considered premium when:

# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.

profit = sales_data - cost_data

premium_performance = np.logical_and(profit > 150000,sales_data > 500000)

row,col = np.where(premium_performance)

for row,col in zip(row,col):
  print(stores[row],categories[col],sales_data[row,col])


Bengaluru Electronics 850000
Hyderabad Electronics 780000
Chennai Electronics 920000
Mumbai Electronics 1050000
Pune Electronics 690000


In [215]:
# Question 46: Underperforming Combinations
# A store-category combination is considered underperforming when:

# Sales are below ₹2,50,000
# Profit margin is below 25%
# Find all such combinations.

profit_value = sales_data - cost_data
profit_margin = np.round((profit_value/sales_data) * 100,0)

underperforming = np.logical_and(sales_data < 250000,profit_margin < 25)

row,col = np.where(underperforming)

for row,col in zip(row,col):
  print(stores[row],categories[col],sales_data[row,col])


Pune Furniture 225000


In [216]:
# Question 47: Category Performance Classification
# Create a new array that classifies every sales value as:

new_sales_array = np.where(sales_data > 500000,"High",
                           np.where(sales_data > 250000,"Medium","low"))

print(new_sales_array)


[['High' 'Medium' 'Medium' 'Medium' 'low' 'low']
 ['High' 'Medium' 'Medium' 'Medium' 'low' 'low']
 ['High' 'Medium' 'Medium' 'Medium' 'low' 'low']
 ['High' 'High' 'Medium' 'Medium' 'low' 'Medium']
 ['High' 'Medium' 'Medium' 'low' 'low' 'low']]


In [217]:
# Part 9: Target-Based Analysis
# Use the following category-wise monthly sales targets:

# sales_targets = np.array([
#     800000,  # Electronics
#     450000,  # Groceries
#     320000,  # Clothing
#     300000,  # Furniture
#     200000,  # Beauty
#     230000   # Sports
# ])
# Question 48: Target Comparison
# Compare every store’s category sales against sales_targets.

# Use NumPy broadcasting.
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
sales_target_compare = sales_data >= sales_targets
print(sales_target_compare)


[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [218]:
# Question 49: Target Achievement Matrix
# Create a Boolean array where:

# True means the store achieved the category target
# False means the store failed to achieve the target


target_ach_mat = sales_data > sales_targets
print(target_ach_mat)



[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [219]:
# Question 50: Target Achievement Count
# Calculate the number of categories in which each store achieved its target.

target_ach_mat = sales_data > sales_targets
target_ach_count = target_ach_mat.sum(axis=1)
#print(target_ach_count)

for i in range(len(stores)):
  print(stores[i] ,"-", target_ach_count[i],"store")


Bengaluru - 1 store
Hyderabad - 4 store
Chennai - 2 store
Mumbai - 6 store
Pune - 0 store


In [220]:
# Question 51: Best Target-Performing Store
# Find the store that achieved the highest number of category targets.

target_ach_mat = sales_data > sales_targets
Best_target_ach_mat = np.argmax(target_ach_mat.sum(axis=1))
print(target_ach_mat.sum(axis=1))
print(stores[Best_target_ach_mat])


[1 4 2 6 0]
Mumbai


In [221]:
# Question 52: Target Achievement by Category
# Calculate how many stores achieved the target for each product category.

target_cat = sales_data > sales_targets
target_ach_cat = target_cat.sum(axis=0)
print(target_ach_cat)

for i in range(len(categories)):
  print(categories[i],":",target_ach_cat[i],)


[3 2 2 2 2 2]
Electronics : 3
Groceries : 2
Clothing : 2
Furniture : 2
Beauty : 2
Sports : 2


In [222]:
# Question 53: Sales Target Variance
# Calculate the difference between actual sales and target sales for every store.

# Use:

# Variance = Actual Sales - Target Sales

variance = sales_data - sales_targets
print("Sales Target Variance- ","\n",variance)



Sales Target Variance-  
 [[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [223]:
# Question 54: Percentage Above or Below Target
# Calculate the percentage variance from the target using:

# Percentage Variance =
# (Actual Sales - Target Sales) / Target Sales × 100

percent_variance = np.round((sales_data - sales_targets) / sales_targets * 100,2)
print(percent_variance)


[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


In [224]:
# Question 55: Stores Missing Electronics Target
# Identify stores that failed to achieve the Electronics sales target.


ele_values = sales_data[:,0]

Stores_Missing_Electronics_Target = ele_values < sales_targets[0]

rows = np.where(Stores_Missing_Electronics_Target)[0]

for r in rows:
  print(stores[r],":",ele_values[r])


Hyderabad : 780000
Pune : 690000


In [225]:
# Question 56: Stores Achieving All Targets
# Check whether any store achieved its target in all six product categories.

# Use np.all().

All_Targets = sales_data > sales_targets
Stores_Achieving_All_Targets = np.all(All_Targets,axis=1)

for i,j in zip(stores,Stores_Achieving_All_Targets):
  if j:
    print(i)


Mumbai


In [226]:
# Question 57: Stores Achieving At Least One Target
# Identify stores that achieved at least one category target.

# Use np.any().
All_Targets = sales_data > sales_targets
Stores_Achieving_At_Least_One_Target = np.any(All_Targets,axis=1)

for i,j in zip(stores,Stores_Achieving_At_Least_One_Target):
  if j:
    print(i)


Bengaluru
Hyderabad
Chennai
Mumbai


In [227]:
# # Part 10: Discount Scenario
# # SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

# Question 58: Discount Amount Matrix
# Calculate the discount amount for each store-category combination.

# Use broadcasting.

Discount_Amount_Matrix = sales_data * discount_rates
print(Discount_Amount_Matrix)


[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [228]:
# Question 59: Sales After Discount
# Calculate the net sales value after applying the category-wise discounts.


Discount_Amount_Matrix = sales_data * discount_rates
net_sales = sales_data - Discount_Amount_Matrix
print(net_sales)


[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [229]:
# Question 60: Profit After Discount
# Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

Discount_Amount_Matrix = sales_data * discount_rates
net_sales = sales_data - Discount_Amount_Matrix
new_profit = net_sales - cost_data
print(new_profit)


[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [230]:
# Question 61: Profit Margin After Discount
# Calculate the new profit margin after applying discounts.
#Profit Margin = (New Profit / Net Sales) * 100

profits = sales_data - cost_data
discount = sales_data * discount_rates
net_sales = sales_data - discount
new_profits = profits - discount

profit_margin = np.round((new_profits / net_sales) * 100,2)
print(profit_margin)


[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


In [231]:
# Question 62: Loss-Making Transactions
# Check whether any store-category combination becomes loss-making after discounts.

# Display the affected store and category names.

discount = sales_data * discount_rates
new_sales = sales_data - discount
new_profit = new_sales - cost_data
loss_making = new_profit < 0
#print(loss_making)

rows,col = np.where(loss_making)

for rows,col in zip(rows,col):
  print(stores[rows],categories[col])
else:
  print("No Loss Making")


No Loss Making


In [232]:
# Question 63: Discount Impact
# Calculate how much total revenue the company loses because of the proposed discounts.

proposed_discount = sales_data -  new_sales
new_sales = sales_data - discount
discount = sales_data * discount_rates

company_losses = np.sum(proposed_discount)

print(company_losses)



1146350.0


In [233]:
# Question 64: Store Most Affected by Discounts
# Identify the store that loses the highest amount of revenue due to discounts.

discount = sales_data * discount_rates
# print(discount)
stores_discount_loss = discount.sum(axis=1)
store_most_affected = np.argmax(stores_discount_loss)
print("Store Most Affected by Discounts is",stores[store_most_affected])

Store Most Affected by Discounts is Mumbai


In [234]:
# Part 11: Tax and Price Adjustment
# The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
# Question 65: Tax Collection Matrix
# Calculate the tax collected on sales for each store and category.

tax_collected = sales_data * tax_rates
print('Tax Collection Matrix:',"\n",tax_collected)


Tax Collection Matrix: 
 [[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [235]:
# Question 66: Sales Including Tax
# Calculate the final customer billing value after adding tax.

Sales_Including_Tax = sales_data + (sales_data * tax_rates)
print("Sales Including Tax:","\n",Sales_Including_Tax)


Sales Including Tax: 
 [[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [236]:
# Question 67: Store-Wise Tax Collection
# Calculate the total tax collected by each store.

stores_tax_collection = sales_data * tax_rates
Store_Wise_Tax_Collection = np.sum(stores_tax_collection,axis=1)
print(Store_Wise_Tax_Collection)

for store,tax in zip(stores,Store_Wise_Tax_Collection):
  print(store,":", tax)

[321900. 321200. 331800. 401400. 274650.]
Bengaluru : 321900.0
Hyderabad : 321200.0
Chennai : 331800.0
Mumbai : 401400.0
Pune : 274650.0


In [237]:
# Question 68: Category-Wise Tax Collection
# Calculate total tax collected for each category.

Tax_Collection = sales_data - (sales_data * tax_rates)
Category_Wise_Tax_Collection = np.sum(Tax_Collection,axis=0)
print(Category_Wise_Tax_Collection)
print("\nCategory-Wise Tax Collection for respective stores")
print("\n")
for store,tax in zip(stores,Category_Wise_Tax_Collection):
  print(store,":",tax)


[3517800. 2075750. 1408000. 1160300.  828200. 1034000.]

Category-Wise Tax Collection for respective stores


Bengaluru : 3517800.0
Hyderabad : 2075750.0
Chennai : 1408000.0
Mumbai : 1160300.0
Pune : 828200.0


In [238]:
# Question 69: Highest Tax-Contributing Store
# Identify the store that contributes the highest tax amount.

tax_store_wise_sales = (sales_data * tax_rates)
Total_tax_store_wise_sales = np.sum(tax_store_wise_sales,axis=1)
Highest_Tax_Contributing_Store = np.argmax(Total_tax_store_wise_sales)

print("Highest_Tax_Contributing_Store:",stores[Highest_Tax_Contributing_Store])


Highest_Tax_Contributing_Store: Mumbai


In [239]:
# Part 12: Array Modification
# Question 70: Updated Pune Electronics Sales
# The Pune store reports that its Electronics sales were entered incorrectly.

# Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

# Make the change in a copied array without modifying the original array.

# original_array = sales_data[-1,0]
# updated_value = original_array = 740000
# print(updated_value)

updated_array = sales_data.copy()

updated_array[stores=="Pune",categories=="Electronics"] = 740000
print("sales data:","\n",sales_data)
print("updated data:","\n",updated_array)


sales data: 
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
updated data: 
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


In [240]:
# Question 71: Revised Beauty Cost
# Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

# Create an updated cost array.

Original_array = cost_data
copied_array = cost_data.copy()

copied_array[:,categories=="Beauty"] = copied_array[:,categories=="Beauty"] * 0.92
print("Cost data: ","\n",cost_data[:,categories=="Beauty"])
print("Copied Or Updated data: ","\n",copied_array[:,categories=="Beauty"])


Cost data:  
 [[125000]
 [140000]
 [120000]
 [165000]
 [115000]]
Copied Or Updated data:  
 [[115000]
 [128800]
 [110400]
 [151800]
 [105800]]


In [241]:
# Question 72: Furniture Cost Increase
# Furniture costs increase by 12% for all stores.

# Update only the Furniture column.

original_cost = cost_data
updated_cost = cost_data.copy()

updated_cost[:,categories=="Furniture"]= updated_cost[:,categories=="Furniture"] * 1.12
print("original_cost:","\n",original_cost[:,categories=="Furniture"])
print("updated_cost","\n",updated_cost[:,categories=="Furniture"])

original_cost: 
 [[205000]
 [225000]
 [195000]
 [250000]
 [170000]]
updated_cost 
 [[229600]
 [252000]
 [218400]
 [280000]
 [190400]]


In [242]:
# Question 73: Store Closure Simulation
# Assume the Pune store is temporarily closed.

# Remove Pune’s sales and cost data from the analysis using np.delete().

original_sales_data = sales_data
copied_sales_data = sales_data.copy()
original_cost_data = cost_data
copied_cost_data = cost_data.copy()

updated_sales_data = np.delete(copied_sales_data,stores=="Pune",axis=0)
updated_cost_data = np.delete(copied_cost_data,stores=="Pune",axis=0)

print("\nsales_data","\n",sales_data)
print("\nupdated_sales_data","\n",updated_sales_data)
print("\ncost data","\n",cost_data)
print("\nupdated_cost_data","\n",updated_cost_data)



sales_data 
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

updated_sales_data 
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]

cost data 
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

updated_cost_data 
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [243]:
# Question 74: Adding a New Store
# A new Delhi store is opened with the following data:

# delhi_sales = np.array([
#     880000, 475000, 330000, 290000, 215000, 250000
# ])

# delhi_cost = np.array([
#     665000, 360000, 235000, 215000, 145000, 180000
# ])
# Add Delhi to both arrays using np.vstack().

# Also add "Delhi" to the stores array.

delhi_sales = np.array([880000, 475000, 330000, 290000, 215000, 250000])
delhi_cost = np.array([665000, 360000, 235000, 215000, 145000, 180000])

Add_delhi_sales = np.vstack((sales_data,delhi_sales))
Add_delhi_cost = np.vstack((cost_data,delhi_cost))

Add_stores = np.append(stores,"Delhi")
# print(stores)
print(Add_stores)
print("\nDelhi array added to sales data:","\n",Add_delhi_sales)
print("Delhi array added to cost data:","\n",Add_delhi_cost)



['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']

Delhi array added to sales data: 
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
Delhi array added to cost data: 
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


In [244]:
# Question 75: Adding a New Product Category
# SmartMart starts selling Home Appliances.

# home_appliance_sales = np.array([
#     360000,
#     325000,
#     390000,
#     420000,
#     295000
# ])

# home_appliance_cost = np.array([
#     265000,
#     240000,
#     285000,
#     305000,
#     225000
# ])
# Add the new category as a column using np.column_stack() or np.hstack().


home_appliance_sales = np.array([360000,
                                 325000,
                                 390000,
                                 420000,
                                 295000])
home_appliance_cost = np.array([265000,
                                240000,
                                285000,
                                305000,
                                225000])

Add_category = np.append(categories,"Home_Appliance")
Add_home_appliance_sales = np.hstack((sales_data,home_appliance_sales.reshape(-1,1)))
Add_home_appliance_cost = np.hstack((cost_data,home_appliance_cost.reshape(-1,1)))

print(Add_category)
print("Added_home_appliance_sales","\n",Add_home_appliance_sales)
print("Added_home_appliance_cost:","\n",Add_home_appliance_cost)


['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home_Appliance']
Added_home_appliance_sales 
 [[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
Added_home_appliance_cost: 
 [[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


In [245]:
# Part 13: Sorting and Ranking
# Question 76: Sort Stores by Sales
# Sort stores in ascending order based on total sales.

# Display store names and sales totals.

stores_with_total_sales = np.sum(sales_data,axis=1)

sort_stores_with_total_sales = np.argsort(stores_with_total_sales)

print(sort_stores_with_total_sales) ## default is ascending order

for i in sort_stores_with_total_sales:
  print(stores[i],":",stores_with_total_sales[i])


[4 0 1 2 3]
Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


In [246]:
# Question 77: Rank Stores by Profit
# Rank stores from highest to lowest total profit.

# Use np.argsort().

profit = sales_data - cost_data
sum_profits = np.sum(profit,axis=1)
rank_profits = np.argsort(sum_profits)[::-1]
# print(rank_profits)

for i in rank_profits:
  print(stores[i],sum_profits[i])

Mumbai 755000
Hyderabad 610000
Bengaluru 605000
Chennai 600000
Pune 505000


In [247]:
# Question 78: Sort Categories by Revenue
# Sort product categories from highest to lowest total revenue.

sum_revenue = np.sum(sales_data,axis=0)
# print(sum_revenue)
sort_sum_revenue = np.argsort(sum_revenue)[::-1]
# print(sort_sum_revenue)
print("Sort Categories by Revenue from high-low:")
for i in sort_sum_revenue:
  print(categories[i],sum_revenue[i])


Sort Categories by Revenue from high-low:
Electronics 4290000
Groceries 2185000
Clothing 1600000
Furniture 1415000
Sports 1175000
Beauty 1010000


In [248]:
# Question 79: Top Three Store-Category Sales
# Find the three highest individual sales values in the complete sales matrix.

# Display their:

# Sales value
# Store name
# Category name

new_sales = sales_data.flatten()
# print(new_sales)
sort_new_sales_index = np.argsort(new_sales)[-3:][::-1]
# print(sort_new_sales_index)
for i in sort_new_sales_index:
  row,col = np.unravel_index(i,sales_data.shape)

  print("Sales value:",sales_data[row,col],
        "\nStore name:",stores[row],
        "\nCategory name:",categories[col])



Sales value: 1050000 
Store name: Mumbai 
Category name: Electronics
Sales value: 920000 
Store name: Chennai 
Category name: Electronics
Sales value: 850000 
Store name: Bengaluru 
Category name: Electronics


In [249]:
# Question 80: Bottom Three Profits
# Find the three lowest profit values in the profit matrix.

profits = sales_data - cost_data
new_profits_flat = profits.flatten()
Three_lowest_profit_matrix = np.argsort(new_profits_flat)[0:4]
# print(Three_lowest_profit_matrix)
print("Bottom Three Profits - ")
for i in Three_lowest_profit_matrix:
  row,col = np.unravel_index(i,profits.shape)
  print("Store Name:",stores[row],
        "\nCategory:",categories[col],
        "\nprofit value:",profits[row,col])


Bottom Three Profits - 
Store Name: Pune 
Category: Furniture 
profit value: 55000
Store Name: Pune 
Category: Sports 
profit value: 60000
Store Name: Chennai 
Category: Sports 
profit value: 60000
Store Name: Pune 
Category: Beauty 
profit value: 60000


In [250]:
from os import sep
# Part 14: Statistical Analysis
# Question 81: Sales Statistics
# Calculate the following for the complete sales array:

# Minimum
# Maximum
# Mean
# Median
# Standard deviation
# Variance
# 25th percentile
# 50th percentile
# 75th percentile

mini_sales = np.min(sales_data)
max_sales = np.max(sales_data)
mean_sales = np.mean(sales_data)
median_sales = np.median(sales_data)
std_sales = np.std(sales_data)
variace_sales = np.var(sales_data)
twentyfivth_percentile = np.percentile(sales_data,25)
fifith_percentile = np.percentile(sales_data,50)
seventyfive_percentile = np.percentile(sales_data,75)

print(mini_sales,max_sales,mean_sales,
      median_sales,std_sales,variace_sales,
      twentyfivth_percentile,fifith_percentile,
      seventyfive_percentile,sep="\n")


175000
1050000
389166.6666666667
302500.0
230322.53954448793
53048472222.222206
228750.0
302500.0
416250.0


In [251]:
# Question 82: Store-Wise Standard Deviation
# Calculate the sales standard deviation for every store.

# Use this value to determine which store has the most variation between product categories.

Store_Wise_Standard_Deviation = np.std(sales_data,axis=1)
# print(Store_Wise_Standard_Deviation)
max_store = np.argmax(Store_Wise_Standard_Deviation)

print("Store with high variance:",stores[max_store])
print("Standard Deviation:", Store_Wise_Standard_Deviation[max_store])


Store with high variance: Mumbai
Standard Deviation: 271860.871280391


In [252]:
# Question 83: Category-Wise Standard Deviation
# Determine which product category has the highest variation in sales across stores.

Category_Wise_Standard_Deviation = np.std(sales_data,axis=0)
high_std = np.argmax(Category_Wise_Standard_Deviation)


print("Category with high variance:",categories[high_std])
print("Standard Deviation:", Category_Wise_Standard_Deviation[high_std])


Category with high variance: Electronics
Standard Deviation: 122539.78945632312


In [253]:
# Question 84: Sales Above Company Average
# Calculate the company-wide average sales value.

# Count how many store-category sales values are above this average.

company_avg = round(np.mean(sales_data),2)

above_avg = np.sum(sales_data > company_avg)

print(company_avg)
print(above_avg)

389166.67
10


In [254]:
# Question 85: Outlier Detection
# Treat any sales value greater than:

# Mean + 1.5 × Standard Deviation
# as a high-value outlier.

# Identify all such sales values.

mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
outlier_detection = mean_sales + 1.5 * std_sales
# print(outlier_detection)
store_having_outlier = sales_data[sales_data > outlier_detection]
print(store_having_outlier)


[ 850000  780000  920000 1050000]


In [255]:
# Part 15: Reshaping and Transformation
# Question 86: Flatten Sales Data
# Convert the two-dimensional sales array into a one-dimensional array using:

# flatten()
# ravel()
# Explain the difference between the two methods.

faltten_array = sales_data.flatten()
ravel_array = sales_data.ravel()

print(faltten_array,)
print(ravel_array)

## for flatten takes a copy
## for ravel takes a reference

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [256]:
# Question 87: Reshape Sales Data
# Reshape the 5 × 6 sales array into:

# 3 × 10
# 10 × 3
# 2 × 15
# 15 × 2
# Verify that no data is lost.

# 3 X 10 array
sales1 = sales_data.reshape(3,10)
sales2 = sales_data.reshape(10,3)
sales3 = sales_data.reshape(2,15)
sales4 = sales_data.reshape(15,2)

print("Original sales data size-",sales_data.size)
print(sales1.size,sales2.size,sales3.size,sales4.size,sep="\n")


Original sales data size- 30
30
30
30
30


In [257]:
# Question 88: Transpose Sales Data
# Transpose the sales array so that:

# Rows represent product categories
# Columns represent stores
# Display the new shape.

Sales_array = sales_data.T

print(Sales_array,Sales_array.shape,sep="\n")

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(6, 5)


In [258]:
# Question 89: Combined Sales and Cost Array
# Stack sales_data and cost_data vertically.

# Display the resulting shape.

New_sales = np.vstack((sales_data,cost_data))

print(New_sales,New_sales.shape,sep="\n")

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


In [259]:
# Question 90: Store-Level Combined Data
# Create a three-dimensional array where:

# First layer contains sales data
# Second layer contains cost data
# Use np.stack().

# Display the shape of the new array.

New_array = np.stack((sales_data,cost_data))
print("Shape:",New_array.shape)
print("Dimiensional:",New_array.ndim)

Shape: (2, 5, 6)
Dimiensional: 3


In [260]:
# Part 16: Missing Data Scenario
# The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
# Question 91: Missing Value Detection
# Find:

# Total number of missing values
# Location of missing values
# Stores and categories containing missing values

total_missing_values = np.sum(np.isnan(sales_with_missing))
print("Total number of missing values:",total_missing_values)

row,col = np.where(np.isnan(sales_with_missing))

print("\nLocation of missing values:")
for r,c in zip(row,col):
  print(r,c)

print("\nStores and categories containing missing values:")
for r,c in zip(row,col):
  print(stores[r],categories[c])


Total number of missing values: 4

Location of missing values:
0 2
1 3
3 1
4 4

Stores and categories containing missing values:
Bengaluru Clothing
Hyderabad Furniture
Mumbai Groceries
Pune Beauty


In [261]:
# Question 92: Replace Missing Values with Zero
# Replace all missing sales values with zero.

Filled_values = np.nan_to_num(sales_with_missing,nan=0)
print(Filled_values)


[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [262]:
# Question 93: Replace with Company Average
# Replace missing values with the overall average of available sales values.

# Use np.nanmean().

avg_value = round(np.nanmean(sales_with_missing),2)
filled_avg_value = np.nan_to_num(sales_with_missing,nan=avg_value)
print(filled_avg_value)


[[ 850000.    420000.    398846.15  275000.    190000.    225000.  ]
 [ 780000.    460000.    295000.    398846.15  210000.    240000.  ]
 [ 920000.    390000.    340000.    260000.    185000.    215000.  ]
 [1050000.    398846.15  375000.    345000.    250000.    290000.  ]
 [ 690000.    405000.    280000.    225000.    398846.15  205000.  ]]


In [263]:
# Question 94: Replace with Category Average
# Replace each missing value with the average sales value of its respective product category.

avg_value = np.nanmean(sales_with_missing,axis=0)
print("Category Average:")
print(avg_value)
print("\n Missing vales")
print(sales_with_missing)
print("\nReplacing the value of respective:")
Filled_Values = sales_with_missing.copy()

row,col = np.where(np.isnan(sales_with_missing))

for r,c in zip(row,col):
  Filled_Values[r,c] = avg_value[c]
print(Filled_Values)


Category Average:
[858000. 418750. 322500. 276250. 208750. 235000.]

 Missing vales
[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]

Replacing the value of respective:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [264]:
# Question 95: Missing Value Impact
# Compare total sales before and after replacing missing values with zero.

total_sales_with_missing = np.nansum(sales_with_missing)
sales_after_filled = np.nansum(np.nan_to_num(sales_with_missing,nan=0))
print("Total sales without filling:")
print(total_sales_with_missing)
print("\nTotal sales after filling:")
print(sales_after_filled)
print("\nDifference:")
print(total_sales_with_missing - sales_after_filled)

## Replacing missing values with 0 does not change
## the total sales when compared with np.nansum(),
## because np.nansum() already ignores the missing values
### and effectively treats them as 0 during summation.



Total sales without filling:
10370000.0

Total sales after filling:
10370000.0

Difference:
0.0


In [265]:
# Part 17: Conditional Business Decisions
# Question 96: Store Performance Labels
# Classify each store based on total sales:

# "Excellent": Total sales above ₹28,00,000
# "Good": Total sales between ₹24,00,000 and ₹28,00,000
# "Needs Improvement": Total sales below ₹24,00,000
# Use np.select().

total_sales = np.sum(sales_data,axis=1)
# print(total_sales)

conditions = [total_sales > 2800000,
              total_sales < 2400000,
              (total_sales > 2400000) & (total_sales < 2800000)]
choice = ["Excellent","Needs Improvement","Good"]

result = np.select(conditions,choice,default="Unknown")

for store, sales, label in zip(stores, total_sales, result):
  print(store, ":", sales, "->", label)


Bengaluru : 2270000 -> Needs Improvement
Hyderabad : 2295000 -> Needs Improvement
Chennai : 2310000 -> Needs Improvement
Mumbai : 2820000 -> Excellent
Pune : 1980000 -> Needs Improvement


In [266]:
# Question 97: Profitability Classification
# Classify each store-category combination as:

# "Highly Profitable": Profit above ₹2,00,000
# "Profitable": Profit between ₹1,00,000 and ₹2,00,000
# "Low Profit": Profit below ₹1,00,000
# "Loss": Profit below zero

profits = sales_data - cost_data
# print(profits)

conditions = [profits > 200000,
             (profits > 100000) & (profits < 200000),
             profits < 100000]

choice = ["Highly Profitable","Profitable","Low Profit"]

Profitability_Classification = np.select(conditions,choice,default="Loss")
print(Profitability_Classification)


[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [267]:
# Question 98: Expansion Recommendation
# A store is eligible for expansion when:

# Total sales are above ₹25,00,000
# Total profit is above ₹7,00,000
# Overall profit margin is above 25%
# Identify eligible stores.

#profit_margin = (total_profit / total_sales) * 100

Total_Sales = np.sum(sales_data,axis=1)
Total_Profits = np.sum((sales_data - cost_data),axis=1)
Profit_Margin = np.round((Total_Profits / Total_Sales) * 100,2)
# print(Total_Sales)
# print(Total_Profits)
# print(Profit_Margin)

Store_Expansion_Recommended = ((Total_Sales > 2500000) & (Total_Profits > 700000) & (Profit_Margin > 25))

for i in stores[Store_Expansion_Recommended]:
  print("Store Name:", i)


Store Name: Mumbai


In [268]:
# Question 99: Category Promotion Recommendation
# A product category should receive additional promotion when:

# Average sales are below ₹3,00,000
# Profit margin is above 25%
# Identify the categories that satisfy these conditions.

Average_sales = np.mean(sales_data,axis=0)
# print(Average_sales)
Total_Sales = np.sum(sales_data,axis=0)
Total_Profits = np.sum((sales_data - cost_data),axis=0)
Profit_Margin = np.round((Total_Profits/Total_Sales) * 100,2)
# print(Profit_Margin)

Category_Promotion_Recommendation = ((Average_sales < 300000) &
                                     (Profit_Margin > 25))

for i in categories[Category_Promotion_Recommendation]:
  print("Category Promotion Recommendation:", i )

Category Promotion Recommendation: Furniture
Category Promotion Recommendation: Beauty
Category Promotion Recommendation: Sports


In [269]:
# Question 100: Cost Optimization Recommendation
# Find store-category combinations where:

# Cost is greater than ₹2,50,000
# Profit margin is below 25%
# These combinations should be reviewed for cost optimization.


Profits = sales_data - cost_data
Profit_Margin = np.round((Profits / sales_data) * 100,2)

Cost_Optimization_Recommendation = ((cost_data > 250000) &
                                    (Profit_Margin < 25))


row,col = np.where(Cost_Optimization_Recommendation)
print("Cost Optimization Recommended:")
for r,c in zip(row,col):
  print(stores[r],":",categories[c])


Cost Optimization Recommended:
Bengaluru : Electronics
Hyderabad : Electronics
Hyderabad : Groceries
Chennai : Electronics
Chennai : Groceries
Mumbai : Electronics
Mumbai : Groceries
Pune : Electronics
Pune : Groceries


In [270]:
# Part 18: Inventory Scenario
# Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

# Question 101: Closing Stock
# Calculate closing stock using:

# Closing Stock = Opening Stock - Units Sold

closing_stock = opening_stock - units_sold

print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [271]:
# Question 102: Low-Stock Identification
# Identify store-category combinations where closing stock is below 30 units.

closing_stock = opening_stock - units_sold
Stock_Identification = closing_stock < 30
# print(Stock_Identification)
row,col = np.where(Stock_Identification)
print("Store : Categories : closing_stock")
for r,c in zip(row,col):
  print(stores[r],":",
        categories[c],":",
        closing_stock[r,c], end="\n")


Store : Categories : closing_stock
Bengaluru : Electronics : 25
Bengaluru : Furniture : 25
Hyderabad : Electronics : 25
Hyderabad : Furniture : 25
Chennai : Electronics : 25
Chennai : Furniture : 25
Mumbai : Electronics : 25
Pune : Electronics : 25
Pune : Furniture : 20


In [272]:
# Question 103: Stock Availability Percentage
# Calculate the percentage of opening stock that remains unsold.

#Stock_avaliable = (Closing Stock / Opening Stock) * 100

Stock_avaliable = np.round((closing_stock / opening_stock) * 100,2)

print(Stock_avaliable)

[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


In [273]:
# Question 104: Fast-Moving Products
# A product is considered fast-moving when more than 80% of its opening stock has been sold.

# Identify fast-moving store-category combinations.

selling_percentage = (units_sold / opening_stock) * 100
fast_moving_product = selling_percentage > 80
# print(fast_moving_product)

print("Fast Moving Products:")
print("Stores : Categories" )

row,col = np.where(fast_moving_product)
for r,c in zip(row,col):
  print(stores[r],":",categories[c])


Fast Moving Products:
Stores : Categories
Bengaluru : Groceries
Hyderabad : Groceries
Hyderabad : Clothing
Chennai : Electronics
Chennai : Groceries
Chennai : Clothing
Mumbai : Electronics
Mumbai : Groceries
Mumbai : Clothing
Pune : Groceries


In [274]:
# Question 105: Category-Wise Units Sold
# Calculate the total units sold for each product category.

category_units_sold = np.sum(units_sold,axis=0)
# print(category_units_sold)
print("Category-Wise Units Sold")
for c, i in zip(categories, category_units_sold):
  print(c,":",i)


Category-Wise Units Sold
Electronics : 485
Groceries : 1950
Clothing : 1240
Furniture : 345
Beauty : 980
Sports : 720


In [275]:
# Question 106: Store-Wise Units Sold
# Calculate total units sold by each store.

Store_Wise_Units_Sold = np.sum(units_sold,axis=1)
print("Store-Wise Units Sold")

for store,units in zip(stores,Store_Wise_Units_Sold):
  print(store,":",units)

Store-Wise Units Sold
Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950


In [276]:
# Question 107: Best Store by Unit Sales
# Identify the store that sold the highest total number of units.
Store_Wise_Units_Sold = np.sum(units_sold,axis=1)

Best_Store_Wise_Units_Sold = np.argmax(Store_Wise_Units_Sold)
# print(Best_Store_Wise_Units_Sold)

print("Best Store:",stores[Best_Store_Wise_Units_Sold])


Best Store: Mumbai


In [277]:
# Question 108: Reorder Requirement
# A store should reorder a category when closing stock is below 25 units.

# Create a Boolean reorder matrix.

closing_stock = opening_stock - units_sold

reorder_requirement = closing_stock < 25
print(reorder_requirement)

row,col = np.where(reorder_requirement)
print("Reorder Requirement")
print("Store : Category : closing_stock")
for r,c in zip(row,col):
  print(stores[r],categories[c],closing_stock[r,c])


[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]
Reorder Requirement
Store : Category : closing_stock
Pune Furniture 20


In [278]:
# Question 109: Reorder Quantity
# Assume each category must maintain 100 units after reordering.

# Calculate reorder quantities only for combinations where closing stock is below 25.

# For all other combinations, return zero.

closing_stock = opening_stock - units_sold
Reorder_Quantity = np.where(closing_stock < 25,100 - closing_stock,0)

row,col = np.where(Reorder_Quantity)

print("Store : Category : Quantity")

for r,c in zip(row,col):
  print(stores[r],
        categories[c],
        Reorder_Quantity[r,c])


Store : Category : Quantity
Pune Furniture 80


In [279]:
# Part 19: Advanced NumPy Questions
# Question 110: Cumulative Store Sales
# Calculate cumulative category sales for each store using np.cumsum().

Cumulative_Store_Sales = np.cumsum(sales_data,axis=1)
print(Cumulative_Store_Sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [280]:
# Question 111: Cumulative Company Sales
# Flatten the sales array and calculate cumulative company sales.

Flatten_Company_Sales = sales_data.flatten()
Cumulative_Company_Sales = np.cumsum(Flatten_Company_Sales)
print("Cumulative Company Sales:","\n",Cumulative_Company_Sales)


Cumulative Company Sales: 
 [  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [281]:
# Question 112: Sales Difference Between Categories
# Calculate the difference between consecutive category sales for each store using np.diff().


Difference = np.diff(sales_data,axis=1)
print("Sales Difference Between Categories:","\n",Difference)


Sales Difference Between Categories: 
 [[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [282]:
# Question 113: Unique Sales Values
# Find all unique sales values in sales_data.

# Also count the frequency of each value.

unique_sales_values,count = np.unique(sales_data,return_counts=True)
print("Unique Value : Count ")
for u,v in zip(unique_sales_values,count):
  print(u,"-",v)

Unique Value : Count 
175000 - 1
185000 - 1
190000 - 1
205000 - 1
210000 - 1
215000 - 1
225000 - 2
240000 - 1
250000 - 1
260000 - 1
275000 - 1
280000 - 1
290000 - 1
295000 - 1
310000 - 2
340000 - 1
345000 - 1
375000 - 1
390000 - 1
405000 - 1
420000 - 1
460000 - 1
510000 - 1
690000 - 1
780000 - 1
850000 - 1
920000 - 1
1050000 - 1


In [283]:
# Question 114: Search for Specific Sales
# Check whether the value ₹4,20,000 exists in the sales array.

# Return its location.

row,col = np.where(sales_data == 420000)
print("Store Name : Category Name - which is having sales as requested")

for r,c in zip(row,col):
  print(stores[r],categories[c],sep=" - ")

Store Name : Category Name - which is having sales as requested
Bengaluru - Groceries


In [284]:
# Question 115: Compare Sales and Cost
# Create a Boolean array showing whether sales are greater than cost for every combination.

# Verify whether all combinations are profitable using np.all().

profit_array = sales_data > cost_data
print(profit_array)
all_profits = np.all(sales_data > cost_data)
print(all_profits)


[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
True


In [285]:
# Question 116: Clip Profit Values
# For reporting purposes, management wants profit values limited to:

# Minimum: ₹75,000
# Maximum: ₹2,50,000
# Use np.clip() to create a reporting profit array.

profit_data = sales_data - cost_data
print("Original Profit Array","\n",profit_data)
Clip_Profit_Values = np.clip(profit_data,75000,250000)
print("\nClip Profit Array")
print(Clip_Profit_Values)


Original Profit Array 
 [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]

Clip Profit Array
[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [286]:
# Question 117: Normalize Sales Data
# Normalize all sales values using min-max normalization:

# Normalized Sales =
# (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

minimum_sales = np.min(sales_data)
max_sales = np.max(sales_data)

Normalized_sales = np.round((sales_data - minimum_sales) / (max_sales - minimum_sales),2)

print(Normalized_sales)

[[0.77 0.28 0.15 0.11 0.02 0.06]
 [0.69 0.33 0.14 0.15 0.04 0.07]
 [0.85 0.25 0.19 0.1  0.01 0.05]
 [1.   0.38 0.23 0.19 0.09 0.13]
 [0.59 0.26 0.12 0.06 0.   0.03]]


In [287]:
# Question 118: Standardize Sales Data
# Standardize sales using:

# Standardized Sales =
# (Sales - Mean Sales) / Standard Deviation

Standardized_Sales = np.round((sales_data - (np.mean(sales_data))) / np.std(sales_data),2)

print(Standardized_Sales)


[[ 2.    0.13 -0.34 -0.5  -0.86 -0.71]
 [ 1.7   0.31 -0.41 -0.34 -0.78 -0.65]
 [ 2.3   0.   -0.21 -0.56 -0.89 -0.76]
 [ 2.87  0.52 -0.06 -0.19 -0.6  -0.43]
 [ 1.31  0.07 -0.47 -0.71 -0.93 -0.8 ]]


In [288]:
# Question 119: Round Values
# Convert profit margin values into:

# Two decimal places
# Nearest whole number
# Floor values
# Ceiling values

profit_margin = ((sales_data - cost_data) / sales_data) * 100

Two_decimal_places = np.round((profit_margin),2)
print("Two decimal places of profit margin: ","\n",Two_decimal_places)

Nearest_whole_number = np.round(profit_margin)
print("\nNearest whole number of profit margin: ","\n",Nearest_whole_number)

Floor_values = np.floor(profit_margin)
print("\nFloor values of profit margin: ","\n",Floor_values)

Ceiling_values = np.ceil(profit_margin)
print("\nCeiling values of profit margin: ","\n",Ceiling_values)


Two decimal places of profit margin:  
 [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Nearest whole number of profit margin:  
 [[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Floor values of profit margin:  
 [[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Ceiling values of profit margin:  
 [[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [289]:
# Question 120: Save and Load Data
# Save the following arrays as NumPy binary files:

# sales_data.npy
# cost_data.npy
# profit_data.npy
# Load them back and verify that the loaded arrays are equal to the original arrays.

## Saving

profit_data = sales_data - cost_data

np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit_data)

## Loading

sales = np.load("sales_data.npy")
cost = np.load("cost_data.npy")
profit = np.load("profit_data.npy")
print(sales,cost,profit,sep="\n")


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [290]:
# Part 20: Final Retail Analytics Project
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")


# Company Summary
print("Company Summary")
print("---------------")
#Total company sales
print("Total sales: ",np.sum(sales_data))
#Total company cost
print("Total cost: ",np.sum(cost_data))
# Total company profit
print("Total profit: ",np.sum(sales_data - cost_data))
print("\n")

print("BEST-PERFORMING STORE")
print("---------------------")
store_profit = np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
Best_Performing_Index = np.argmax(store_profit)
profits = sales_data - cost_data
profits_margin = np.round((profits/sales_data) * 100,2)
print("Store: ",stores[Best_Performing_Index])
print("Sales: ",sales_data[Best_Performing_Index])
print("Cost: ",cost_data[Best_Performing_Index])
print("Profit: ",profits[Best_Performing_Index])
print("Profit Margin: ",profits_margin[Best_Performing_Index])
print("\n")

print("MOST PROFITABLE CATEGORY")
print("------------------------")
profit_cat_index = np.argmax(np.sum(profits,axis=0))
cat_profits = (np.sum(sales_data,axis=0)) - (np.sum(cost_data,axis=0))
cat_profit_margin = np.round(cat_profits/cost_data * 100,2)
print("Category: ",categories[profit_cat_index])
print("Sales: ",sales_data[profit_cat_index])
print("Cost:", cost_data[profit_cat_index])
print("Profits: ",cat_profits[profit_cat_index])
print("profit Margin: ",cat_profit_margin[profit_cat_index])
print("\n")

print("EXPANSION RECOMMENDATIONS")
print("-------------------------")
# store is eligible for expansion when:
# Total sales are above ₹25,00,000
# Total profit is above ₹7,00,000
# Overall profit margin is above 25%
# Identify eligible stores.

Total_sales = np.sum(sales_data,axis=1)
Total_profits = np.sum((sales_data - cost_data),axis=1)
Profit_Margin = (Total_profits/Total_sales) * 100
Eligible_Stores = ((Total_sales > 2500000) & (Total_profits > 700000) & (Profit_Margin > 25))
row = np.where(Eligible_Stores)
for r in row:
  print("Eligible Stores: ",stores[r])

print("\n")

print("COST OPTIMIZATION")
print("------------------")
# Find store-category combinations where:
# Cost is greater than ₹2,50,000
# Profit margin is below 25%
# These combinations should be reviewed for cost optimization.

profit_margin = np.round((sales_data - cost_data)/sales_data * 100,2)

COST_OPTIMIZATION = ((cost_data > 250000) & (profit_margin < 25))
row,col = np.where(COST_OPTIMIZATION)
for r, c in zip(row,col):
  print("Strore: ",stores[r])
  print("Category: ",categories[c])
  print("Cost: ",cost_data[r,c])
  print("Profit Margin: ",profit_margin[r,c],"%")

print("\n")
print("INVENTORY REORDER")
print("------------------")
Closing_Stock = opening_stock - units_sold
reorder_condition = closing_stock < 25
row,col = np.where(reorder_condition)

for r,c in zip (row,col):
  reorder_quantity = 100 - closing_stock[r,c]
  print("Store: ",stores[r])
  print("Category: ",categories[c])
  print("Closing Stock: ",closing_stock[r,c])
  print("Reorder Quantity: ",reorder_quantity)



SMARTMART RETAIL PERFORMANCE REPORT
Company Summary
---------------
Total sales:  11675000
Total cost:  8600000
Total profit:  3075000


BEST-PERFORMING STORE
---------------------
Store:  Mumbai
Sales:  [1050000  510000  375000  345000  250000  290000]
Cost:  [790000 390000 265000 250000 165000 205000]
Profit:  [260000 120000 110000  95000  85000  85000]
Profit Margin:  [24.76 23.53 29.33 27.54 34.   29.31]


MOST PROFITABLE CATEGORY
------------------------
Category:  Electronics
Sales:  [850000 420000 310000 275000 190000 225000]
Cost: [640000 315000 220000 205000 125000 160000]
Profits:  1040000
profit Margin:  [162.5  166.67 206.82 180.49 276.   212.5 ]


EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:  ['Mumbai']


COST OPTIMIZATION
------------------
Strore:  Bengaluru
Category:  Electronics
Cost:  640000
Profit Margin:  24.71 %
Strore:  Hyderabad
Category:  Electronics
Cost:  590000
Profit Margin:  24.36 %
Strore:  Hyderabad
Category:  Groceries
Cost:  3500